apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: example
spec:
  reference:
    export:
      name: example
      path: root:provider
  permissionClaims:
    - resource: secrets
      all: true
      state: Accepted
