---
apiVersion: v1
kind: Namespace
metadata:
  name: kcp-syncer-kind-1szni5eb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcp-syncer-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
---
apiVersion: v1
kind: Secret
metadata:
  name: kcp-syncer-kind-1szni5eb-token
  namespace: kcp-syncer-kind-1szni5eb
  annotations:
    kubernetes.io/service-account.name: kcp-syncer-kind-1szni5eb
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-syncer-kind-1szni5eb
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "create"
  - "get"
  - "list"
  - "watch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - "get"
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - "create"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - endpoints
  - pods
  - pods/log
  - pods/exec
  - pods/attach
  - pods/binding
  - pods/portforward
  - pods/proxy
  - pods/ephemeralcontainers
  - pods
  - pods/log
  - pods/exec
  - pods/attach
  - pods/binding
  - pods/portforward
  - pods/proxy
  - pods/ephemeralcontainers
  - secrets
  - services
  - services
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-syncer-kind-1szni5eb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-syncer-kind-1szni5eb
subjects:
- kind: ServiceAccount
  name: kcp-syncer-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kcp-dns-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - "create"
  - "get"
  - "list"
  - "update"
  - "delete"
  - "watch"
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - "create"
  - "get"
  - "list"
  - "update"
  - "delete"
  - "watch"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - "create"
  - "get"
  - "list"
  - "update"
  - "delete"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kcp-dns-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kcp-dns-kind-1szni5eb
subjects:
  - kind: ServiceAccount
    name: kcp-syncer-kind-1szni5eb
    namespace: kcp-syncer-kind-1szni5eb
---
apiVersion: v1
kind: Secret
metadata:
  name: kcp-syncer-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: default-cluster
      cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFqTVNFd0h3WURWUVFEREJnNUxqYzAKTGpFeExqSTBMV05oUURFMk56Z3hNVGt5TlRRd0hoY05Nak13TXpBMk1UVXhOREV6V2hjTk1qUXdNekExTVRVeApOREV6V2pBZ01SNHdIQVlEVlFRRERCVTVMamMwTGpFeExqSTBRREUyTnpneE1Ua3lOVFF3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURLK0I3MU9POFpzWDhBRENSMjNBMmpxZWxrdVRaQ1hSQWoKQ3B0VVZ6dGZvREFSRm52TDl0WjRZNWZzejNQRVhMTHRqQmkrdmFDVkg1RW1KbWtxNXV0RVI1QWd4Zk93NFJxYQpRbXJuVTR3Rm5RQWZDNDBsalhkZDd5NXROTGdvSk9kQ2JBN0QzbnJUZ05xSENFU1pNYzNOWUltZzFjTis5eHlOClU1SjRGa2dhY0dNamdlTThEV3E5cFBUUkZwOEZobHlkTjUxK1djKzVlVCtpa1htOXJUVXNGeTRXcUhhU1ZpdVgKK0FmcnBLZm8xRVZoSWxyQ1JCR0hDWW84SDZyYXplUzZCMTh4TVlKZE93UWtNOHdLaHJaeWptbzJ1UjdVOGNBNgpPVXRYVGpvRHovc2IwWDJWQWxibTZ0WDJyY0ZUdW53MDNQeUZZaG9kNjR5YzQxUC9IQ3hoQWdNQkFBR2pjakJ3Ck1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEUKQWpBQU1COEdBMVVkSXdRWU1CYUFGTUJLVmlXUzhaRU9rRkh0Mmh4NDR4em9nYW55TUJvR0ExVWRFUVFUTUJHQwpDV3h2WTJGc2FHOXpkSWNFQ1VvTEdEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFWmVub0J3WXhCRTNSajhXClQ0RkR6WEhKZzZkYXRmU1FNY09zQnZtOVlPM3daQjg1dnFJTDdsRnBaV2VxUkl6T0VBZzAvTTNvZ2xUSmxYcXkKK1cydnRNWTBWdGdQbExUNHF2eUNrK0VrSlJrd2hmRy9mcEdxMmx4MDZ3b2hBT2tlbklLRVFqYXRFb1VQRkVHMApPb1BjeTR5dzFDS2p0LzhCdXp5a0JENXREZ0ZvQnJkU3RHa2tac3pYbStBRTBJV1NWR0J6aFNuSnVwcUtHRlZ4Cnk3NUw0S2tTMllzTW4rcTVPMUF5eTVIb0RDeFBTbkxJdU93ZEh1c3NjSHIyZkNhWEwrL0RFMzhsOXluOS9rYk8KVmFhc3FtT3FGTnhJRThWclpQeHJLbHdwcUdNV2phTGdiOUZnaWMzeHUwaUtFRDFJem43OFhOdzBFY0M4WUZxeApKbVY2YVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FldWdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBak1TRXdId1lEVlFRRERCZzVMamMwCkxqRXhMakkwTFdOaFFERTJOemd4TVRreU5UUXdIaGNOTWpNd016QTJNVFV4TkRFeldoY05NalF3TXpBMU1UVXgKTkRFeldqQWpNU0V3SHdZRFZRUUREQmc1TGpjMExqRXhMakkwTFdOaFFERTJOemd4TVRreU5UUXdnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3kzTzhEdGY5R1JTVmZSUU5Dd3F3cC9sU0hmd2JOCkxmNHR1MkJsZlhGd2Nyd05Ed3JYRVJCMTFBaWswelhwVVZsbXhpUWY5V0xXQTZVTkNBNWxSZlFFOWxZTS84SUoKT0ZDZmJqUDRaSFdMbVlPRUVaalduVjd5TjhpdWFlSTJudm00bGhDUDI3V25XRE1TQndsL0RvTUUzMVQ1MkF3RwpZUURpZFpPTnJ2d2tWaUpOT2F6OGc0UGFUMFVTa2M0azFWY2IzcEhTTGRlb0ZMVlMvMXIvMFdRNG0xRk1rNWVWCnpHSGZvRXR3cHh4NzA1MlY2VTFKQk9uUlVkVWtVaTM2NzhCRHM5WkVSSFdiYnk0V2RuVTB4VTYybFc1ZnZ1Y2QKSkREajB3dDRuRzdPVnFLYitsUzZnV1gvUG1oSW5ScFRyWC9tanNEQUpWdExUR0RKbmVvVTlJdTlBZ01CQUFHagpRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRBClNsWWxrdkdSRHBCUjdkb2NlT01jNklHcDhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsZ3Y0Q2phelBrSXcKMW05clpwUkZEbHJsaFlNRWhWd0lhQ2VraGptU3gvY21FU1JSS0FjR1BabnVDZ3hBa3JZVFo2UkkzRFZ5RHhyRwpmeEVianVhVXF1Z1NWMG9mMUV4RURYTnUwdmRjeFl6YXFTOTNJM2RPZmdmUk1vSnhpbkxmUGRoQTVLcS84UFBHCm1hZzFPbmw4L3cycVlySnpmODBwQ3l0SzFKbG5SUDdlM05vTEV5akgrVGtqbW1HYzVjRGtiL3dtd0FWRUxoSUoKOG8vU1JlaVVtdWpSUVNCUmJkc1RrZ1BVNnpybDN4Qzc3bjM3L1NlSmJVWENUSzlpUEpEL1lXVGVTYkh5R2s5SgpGZHR5YkNyMjNMU2p6YWRjeEN0OGhtK3hLQVp3dERub1phb0x0d0s4cUcwZG5nQXVRblFrOWhaNCt0bjBJUkZ5CkRYMVZST0JOcXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://9.74.11.24:6443
    contexts:
    - name: default-context
      context:
        cluster: default-cluster
        namespace: default
        user: default-user
    current-context: default-context
    users:
    - name: default-user
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9GaTFja09INk5MUGQtOWkydUpYN295S1ZZSUtRX3dibWFjUERFaUxqN1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9jbHVzdGVyTmFtZSI6IjExN2xwOWpoZzlnaDdkeGoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L25hbWVzcGFjZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoia2NwLXN5bmNlci1raW5kLTFzem5pNWViLXRva2VuLXFkdGZwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImtjcC1zeW5jZXIta2luZC0xc3puaTVlYiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhmMzE1NDlmLWFjZmEtNGFiOS05Y2FhLWI4MGJjNjA1YTFmZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmtjcC1zeW5jZXIta2luZC0xc3puaTVlYiJ9.SbHBwit6lWxeVnP5TFnpTEvE3YxaDcl4acLWAU-aLrVVaPZDEsL7NIHUfJ6J75sGaM1H55xFFrxBe_NQITbFGBnozJrRIVECRBZHnRL9jePQQoxEtoAhuLu7FQ9o1D5NA7YTZ5c8vuHLMJCJG2-ILaS-KKypr1sruPbkIoletRhTJXp3cyWw9cTEn3nqUQFALSKakIqnaul2qvTV9YvdZXbyiR-JjA9GDgsoFXxHCboIO5p5G3Ypw3sZqnLkPNq4Gy88LCQ9klhflXtMd9jGFRTYtDIbP-DJeTBhb1z7hKY8aVmj1O9KP07r7B4W9Vh5hr605J2vqK-haVf24S-djjqjTIeKSEIYOFOxJkhIvqqiRsmBzAQEZLlRLKJ_Wew60E3BrYSYK7J2V_yREZEME9e3cjdcnnzd6NGtRFhyDq5AKvQ3WfQ1AK3IWgMTIES917gidovmzPEdih7ugOd7VP-RaK3XRmjZX5sVOJQwc8AdPWomgd7G30gQF4dNzsoIf_nBDGEC2RqLq9DYqac63SbDRmbDL4wMwo_2OnmS5djapzgkY-O28oXHAQ42KSM-FfbGBB8mYSvddyRWgIrS8VmRCU3oJL9XVh_YRt2wJKr5lbp12HC9MqOZbIdaXmoE9lo49uAJxIeJkcD2h2rU-GHPtlxJhaqelW_-_F3hn-8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp-syncer-kind-1szni5eb
  namespace: kcp-syncer-kind-1szni5eb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kcp-syncer-kind-1szni5eb
  template:
    metadata:
      labels:
        app: kcp-syncer-kind-1szni5eb
    spec:
      containers:
      - name: kcp-syncer
        command:
        - /ko-app/syncer
        args:
        - --from-kubeconfig=/kcp/kubeconfig
        - --sync-target-name=kind
        - --sync-target-uid=47edf1c1-fd9f-430b-aade-c598f8d06d37
        - --from-cluster=117lp9jhg9gh7dxj
        - --api-import-poll-interval=1m0s
        - --downstream-namespace-clean-delay=30s
        - --resources=poddisruptionbudgets.policy
        - --resources=horizontalpodautoscalers.autoscaling
        - --resources=services
        - --resources=endpoints
        - --resources=pods
        - --qps=20
        - --burst=30
        - --feature-gates=KCPSyncerTunnel=true
        - --dns-image=kind.local/syncer
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kind.local/syncer
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: kcp-config
          mountPath: /kcp/
          readOnly: true
      serviceAccountName: kcp-syncer-kind-1szni5eb
      volumes:
        - name: kcp-config
          secret:
            secretName: kcp-syncer-kind-1szni5eb
            optional: false
