apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default
rules:
#  - apiGroups:
#      - ""
#    resources:
#      - "*"
#    verbs:
#      - "*"
  - apiGroups:
      - apis.kcp.io
    resources:
      - apiexports/content
    verbs:
      - "*"

