---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - stable.example.com.stable.example.com
  resources:
  - crontabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.example.com.stable.example.com
  resources:
  - crontabs/finalizers
  verbs:
  - update
- apiGroups:
  - stable.example.com.stable.example.com
  resources:
  - crontabs/status
  verbs:
  - get
  - patch
  - update
